# Generated by Django 2.1 on 2018-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('family', models.IntegerField(default=0)),
                ('resources', models.IntegerField(null=True)),
                ('least_start', models.IntegerField(default=0)),
                ('max_end', models.IntegerField(default=0)),
                ('length', models.IntegerField(default=0)),
                ('start', models.IntegerField(default=0)),
                ('end', models.IntegerField(default=0)),
                ('late_cost', models.IntegerField(default=100)),
                ('early_cost', models.IntegerField(default=0)),
                ('fixed', models.BooleanField()),
                ('color', models.IntegerField(choices=[(1, 'Red'), (2, 'Green'), (3, 'Blue')], default=1)),
            ],
        ),
    ]
